
trigger:
- main

stages:
  - stage: Build
    displayName: Build and Push Image
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: default
          vmImage: ado-linuxagent
        steps:
          - script: echo Building the image...
            displayName: 'Echo Build Start'

          - task: Docker@2
            displayName: Build and Push Docker Image
            inputs:
              containerRegistry: 'dockerhub_registry'
              repository: 'edenmor1989/counter-service'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
  - stage: Test
    displayName: Run Tests
    jobs:
      - job: Test
        displayName: Test
        pool:
          name: default
          vmImage: ado-linuxagent
        steps:
          - script: echo Running Tests...
            displayName: 'Echo Test Start'

          - script: |
              docker pull edenmor1989/counter-service:$(Build.BuildId)
              docker run -d --name test-counter-service -p 8080:80 edenmor1989/counter-service:$(Build.BuildId)
              sleep 1 
            displayName: Start Docker Container

          - script: |
              curl http://localhost:8080
              if [ $? -eq 0 ]; then
                echo "Test Passed"
                exit 0
              else
                echo "Test Failed"
                exit 1
              fi
            displayName: Test Application

          - script: |
              docker stop test-counter-service
              docker rm test-counter-service
            displayName: Cleanup Test Container


  - stage: Deploy
    displayName: Deploy to Production
    condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: 'production'
        pool:
          name: default
          vmImage: ado-linuxagent
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deploying to production...
                  displayName: 'Echo Deploy Start'

                - task: SSH@0
                  displayName: 'Deploy to Production Server'
                  inputs:
                    sshEndpoint: 'ssh_prod_server'
                    runOptions: 'commands'
                    commands: |
                      
                      docker pull edenmor1989/counter-service:$(Build.BuildId)
                      docker stop counter-service || true 
                      docker rm counter-service || true
                      docker run -d --name counter-service -p 80:80 edenmor1989/counter-service:$(Build.BuildId)
