version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data 
    ports:
      - "6379:6379"
volumes:
  redis-data: 