apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
      - name: counter-service
        image: edenmor1989/counter-service:persistent3
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis"  # Redis service name
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 
  selector:
    app: counter-service
