apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-counter-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
