apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-counter-service
  labels:
    app: counter-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 
  selector:
    app: counter-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
